"""create users table

Revision ID: 241af093bc14
Revises: 6261975d9960
Create Date: 2026-10-04 11:06:45.326935

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '241af093bc14'
down_revision: Union[str, Sequence[str], None] = '6261975d9960'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), sa.Identity(always=False), nullable=False),
    sa.Column('full_name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=254), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('requester', 'agent', 'manager', name='ck_users_role', native_enum=False, create_constraint=True), server_default=sa.text("'requester'"), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('char_length(btrim(full_name)) >= 2', name='ck_users_full_name_min_length'),
    sa.CheckConstraint('char_length(email) >= 3', name='ck_users_email_min_length'),
    sa.CheckConstraint('email = lower(btrim(email))', name='ck_users_email_normalized'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email', name='uq_users_email')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    # ### end Alembic commands ###
