"""create tickets table

Revision ID: 3403cd22e638
Revises: aa3a7ed3c919
Create Date: 2026-10-04 19:56:39.464782

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3403cd22e638'
down_revision: Union[str, Sequence[str], None] = 'aa3a7ed3c919'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tickets',
    sa.Column('id', sa.Integer(), sa.Identity(always=False), nullable=False),
    sa.Column('title', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('priority', sa.Enum('LOW', 'NORMAL', 'HIGH', name='ck_tickets_priority', native_enum=False, create_constraint=True), server_default=sa.text("'NORMAL'"), nullable=False),
    sa.Column('status', sa.Enum('OPEN', 'IN_PROGRESS', 'RESOLVED', name='ck_tickets_status', native_enum=False, create_constraint=True), server_default=sa.text("'OPEN'"), nullable=False),
    sa.Column('requester_id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('char_length(btrim(description)) BETWEEN 10 AND 5000', name='ck_tickets_description_length'),
    sa.CheckConstraint('char_length(btrim(title)) BETWEEN 5 AND 150', name='ck_tickets_title_length'),
    sa.ForeignKeyConstraint(['requester_id'], ['users.id'], name='fk_tickets_requester_id', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], name='fk_tickets_team_id', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_tickets_requester_id_id', 'tickets', ['requester_id', 'id'], unique=False)
    op.create_index('ix_tickets_team_id_id', 'tickets', ['team_id', 'id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_tickets_team_id_id', table_name='tickets')
    op.drop_index('ix_tickets_requester_id_id', table_name='tickets')
    op.drop_table('tickets')
    # ### end Alembic commands ###
