"""add ticket assignment fields

Revision ID: 4fc9f7a9e50d
Revises: 3403cd22e638
Create Date: 2026-10-04 20:35:58.360163

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4fc9f7a9e50d'
down_revision: Union[str, Sequence[str], None] = '3403cd22e638'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tickets', sa.Column('assignee_id', sa.Integer(), nullable=True))
    op.add_column('tickets', sa.Column('claimed_at', sa.DateTime(timezone=True), nullable=True))
    op.create_foreign_key('fk_tickets_assignee_id', 'tickets', 'users', ['assignee_id'], ['id'], ondelete='RESTRICT')
    op.drop_column('tickets', 'created_at')
    op.create_check_constraint(
        "ck_tickets_assignment_state",
        "tickets",
        "(status = 'OPEN' "
        "AND assignee_id IS NULL AND claimed_at IS NULL) "
        "OR "
        "(status IN ('IN_PROGRESS', 'RESOLVED') "
        "AND assignee_id IS NOT NULL AND claimed_at IS NOT NULL)",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "ck_tickets_assignment_state",
        "tickets",
        type_="check",
    )
    op.add_column('tickets', sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.drop_constraint('fk_tickets_assignee_id', 'tickets', type_='foreignkey')
    op.drop_column('tickets', 'claimed_at')
    op.drop_column('tickets', 'assignee_id')
    # ### end Alembic commands ###
