"""add ticket comments and events

Revision ID: 84ce4ae5dd11
Revises: d456deec21ab
Create Date: 2026-10-05 21:23:40.804427

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '84ce4ae5dd11'
down_revision: Union[str, Sequence[str], None] = 'd456deec21ab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ticket_comments',
    sa.Column('id', sa.Integer(), sa.Identity(always=False), nullable=False),
    sa.Column('ticket_id', sa.Integer(), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('char_length(body) <= 5000 AND char_length(btrim(body)) >= 2', name='ck_ticket_comments_body_length'),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['ticket_id'], ['tickets.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_ticket_comments_ticket_id_id', 'ticket_comments', ['ticket_id', 'id'], unique=False)
    op.create_table('ticket_events',
    sa.Column('id', sa.Integer(), sa.Identity(always=False), nullable=False),
    sa.Column('ticket_id', sa.Integer(), nullable=False),
    sa.Column('actor_id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.Enum('CREATED', 'CLAIMED', 'RESOLVED', 'REOPENED', 'COMMENT_ADDED', name='ck_ticket_events_event_type', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('details', sa.JSON(), server_default=sa.text("'{}'"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['ticket_id'], ['tickets.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_ticket_events_ticket_id_id', 'ticket_events', ['ticket_id', 'id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_ticket_events_ticket_id_id', table_name='ticket_events')
    op.drop_table('ticket_events')
    op.drop_index('ix_ticket_comments_ticket_id_id', table_name='ticket_comments')
    op.drop_table('ticket_comments')
    # ### end Alembic commands ###
