"""create team members table

Revision ID: aa3a7ed3c919
Revises: 241af093bc14
Create Date: 2026-10-04 17:00:15.662270

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aa3a7ed3c919'
down_revision: Union[str, Sequence[str], None] = '241af093bc14'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('team_members',
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], name='fk_team_members_team_id', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='fk_team_members_user_id', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('team_id', 'user_id', name='pk_team_members')
    )
    op.create_index('ix_team_members_user_id', 'team_members', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_team_members_user_id', table_name='team_members')
    op.drop_table('team_members')
    # ### end Alembic commands ###
